Fix linux upstream git url and setup drm-intel remote for nightly
And add more verbose status output if failed.

diff --git a/dim b/dim
--- a/dim
+++ b/dim
@@ -100,7 +100,7 @@ drm_intel_upstream_git=git://anongit.freedesktop.org/drm-intel
 #drm_upstream_git=git://people.freedesktop.org/~airlied/linux
 #sound_upstream_git=git://git.kernel.org/pub/scm/linux/kernel/git/tiwai/sound.git
 #driver_core_upstream_git=git://git.kernel.org/pub/scm/linux/kernel/git/gregkh/driver-core.git
-#linux_upstream_git=git://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git
+linux_upstream_git=git://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git
 
 vfio_upstream_git=https://github.com/awilliam/linux-vfio.git
 kvm_upstream_git=git://git.kernel.org/pub/scm/virt/kvm/kvm.git
@@ -227,23 +227,20 @@ function update_linux_next
 	
 	# always update gvt-fixes
 	echo -n "Pushing gvt-fixes to for-drm-intel-fixes... "
-	git push $DRY_RUN origin +origin/gvt-fixes:for-drm-intel-fixes >& /dev/null
-	echo "Done."
+	git push $DRY_RUN origin +origin/gvt-fixes:for-drm-intel-fixes >& /dev/null && echo "Done." || echo "Fail"
 
 	if git merge-base --is-ancestor origin/gvt-next-fixes origin/gvt-fixes ; then
 		# -fixes has caught up to dinf, i.e. we're out of the merge
 		# window. Push the next queue.
 		echo -n "Out of merge window. Pushing gvt-next to for-drm-intel-next-queued... "
-		git push $DRY_RUN origin +origin/gvt-next:for-drm-intel-next-queued >& /dev/null
-		echo "Done."
+		git push $DRY_RUN origin +origin/gvt-next:for-drm-intel-next-queued >& /dev/null && echo "Done." || echo "Fail"
 	else
 		# dinf is ahead of -fixes, i.e. drm-next has already closed for
 		# the next merge window and we've started to gather new fixes
 		# for the current -next cycle. Push dinf
 
 		echo -n "Pushing gvt-next-fixes to for-drm-intel-next-fixes... "
-		git push $DRY_RUN origin +origin/gvt-next-fixes:for-drm-intel-next-fixes >& /dev/null
-		echo "Done."
+		git push $DRY_RUN origin +origin/gvt-next-fixes:for-drm-intel-next-fixes >& /dev/null && echo "Done." || echo "Fail"
 	fi
 }
 
@@ -358,7 +355,7 @@ function dim_rebuild_nightly
 	echo "Done."
 
 	echo -n "Pushing $integration_branch... "
-	git push $DRY_RUN origin +HEAD >& /dev/null && echo "Done."
+	git push $DRY_RUN origin +HEAD >& /dev/null && echo "Done." || echo "Fail"
 
 	echo -n "Updating rerere cache... "
 	cd $rerere
@@ -373,7 +370,7 @@ function dim_rebuild_nightly
 			echo -n "Nothing changed. "
 		fi
 		echo -n "Pushing rerere cache... "
-		git push $DRY_RUN origin HEAD >& /dev/null && echo "Done."
+		git push $DRY_RUN origin HEAD >& /dev/null && echo "Done." || echo "Fail"
 	else
 		echo "Fail: Branch setup for the gvt-rerere-cache is borked."
 		exit 1
@@ -1025,6 +1022,7 @@ function dim_update_branches
 {
 	cd $DIM_PREFIX/$DIM_GVT_INTEL
 	for remote in $DIM_GVT_INTEL_REMOTE $DIM_DRM_INTEL_UPSTREAM_REMOTE origin; do
+	        echo "Fetching $remote..."
 		git fetch $remote
 	done
 
@@ -1122,7 +1120,11 @@ function dim_setup
 		git checkout -t origin/gvt-nightly
 	fi
 	# check our upstreams
-
+	if git remote | grep $DIM_DRM_INTEL_UPSTREAM_REMOTE > /dev/null ; then
+	        git config remote.$DIM_DRM_INTEL_UPSTREAM_REMOTE.url $drm_intel_upstream_git
+	else
+	        git remote add $DIM_DRM_INTEL_UPSTREAM_REMOTE $drm_intel_upstream_git
+	fi
 	if git remote | grep vfio-upstream > /dev/null ; then
 		git config remote.vfio-upstream.url $vfio_upstream_git
 	else
